export enum cyclesActionTypes {
  CREATE_NEW_CYCLE = 'CREATE_NEW_CYCLE',
  INTERRUPTED_CYCLE = 'INTERRUPTED_CYCLE',
  MARK_CYCLE_AS_FINISHED = 'MARK_CYCLE_AS_FINISHED',
  MANIPULATION_SECONDS = 'MANIPULATION_SECONDS',
}